pipeline {
    agent {
        label "dockerworker"
    }
    stages {
        stage('Build') {
            steps {
                dir("app") {
                    sh 'mvn clean package -Dmaven.test.skip=true'
                }
            }
        }
        stage('Build image') {
            steps {
                sh 'docker build -t my-app .'
            }
        }
        stage('Run app') {
            steps {
                sh 'docker run my-app'
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}