pipeline {
    agent {
        label "dockerworker"
    }
    stages {
        stage('Build') {
            dir("app") {
                sh "pwd"
            }
            steps {
                sh 'mvn clean package -Dmaven.test.skip=true'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Build image') {
            steps {
                sh 'docker build -t my-app .'
            }
        }
        stage('Run app') {
            steps {
                sh 'docker run my-app'
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}